services:
  postgres:
    image: postgres:18.3
    container_name: stride_postgres
    ports:
      - "5432:5432"
    volumes:
      - "stride_postgres:/var/lib/postgresql"
    environment:
      POSTGRES_USER: stride
      POSTGRES_PASSWORD: stride
      POSTGRES_DB: stride

volumes:
  stride_postgres:

