/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingTinyRouteImport } from './routes/onboarding/tiny'
import { Route as OnboardingStrugglesRouteImport } from './routes/onboarding/struggles'
import { Route as OnboardingReminderRouteImport } from './routes/onboarding/reminder'
import { Route as OnboardingIdentityRouteImport } from './routes/onboarding/identity'
import { Route as OnboardingHabitTypeRouteImport } from './routes/onboarding/habit-type'
import { Route as OnboardingHabitBuildRouteImport } from './routes/onboarding/habit-build'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding/done'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingTinyRoute = OnboardingTinyRouteImport.update({
  id: '/tiny',
  path: '/tiny',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStrugglesRoute = OnboardingStrugglesRouteImport.update({
  id: '/struggles',
  path: '/struggles',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingReminderRoute = OnboardingReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingIdentityRoute = OnboardingIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHabitTypeRoute = OnboardingHabitTypeRouteImport.update({
  id: '/habit-type',
  path: '/habit-type',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHabitBuildRoute = OnboardingHabitBuildRouteImport.update({
  id: '/habit-build',
  path: '/habit-build',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/habit-build': typeof OnboardingHabitBuildRoute
  '/onboarding/habit-type': typeof OnboardingHabitTypeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/reminder': typeof OnboardingReminderRoute
  '/onboarding/struggles': typeof OnboardingStrugglesRoute
  '/onboarding/tiny': typeof OnboardingTinyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/habit-build': typeof OnboardingHabitBuildRoute
  '/onboarding/habit-type': typeof OnboardingHabitTypeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/reminder': typeof OnboardingReminderRoute
  '/onboarding/struggles': typeof OnboardingStrugglesRoute
  '/onboarding/tiny': typeof OnboardingTinyRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/habit-build': typeof OnboardingHabitBuildRoute
  '/onboarding/habit-type': typeof OnboardingHabitTypeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/reminder': typeof OnboardingReminderRoute
  '/onboarding/struggles': typeof OnboardingStrugglesRoute
  '/onboarding/tiny': typeof OnboardingTinyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding/done'
    | '/onboarding/habit-build'
    | '/onboarding/habit-type'
    | '/onboarding/identity'
    | '/onboarding/reminder'
    | '/onboarding/struggles'
    | '/onboarding/tiny'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding/done'
    | '/onboarding/habit-build'
    | '/onboarding/habit-type'
    | '/onboarding/identity'
    | '/onboarding/reminder'
    | '/onboarding/struggles'
    | '/onboarding/tiny'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/onboarding/done'
    | '/onboarding/habit-build'
    | '/onboarding/habit-type'
    | '/onboarding/identity'
    | '/onboarding/reminder'
    | '/onboarding/struggles'
    | '/onboarding/tiny'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/tiny': {
      id: '/onboarding/tiny'
      path: '/tiny'
      fullPath: '/onboarding/tiny'
      preLoaderRoute: typeof OnboardingTinyRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/struggles': {
      id: '/onboarding/struggles'
      path: '/struggles'
      fullPath: '/onboarding/struggles'
      preLoaderRoute: typeof OnboardingStrugglesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/reminder': {
      id: '/onboarding/reminder'
      path: '/reminder'
      fullPath: '/onboarding/reminder'
      preLoaderRoute: typeof OnboardingReminderRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/identity': {
      id: '/onboarding/identity'
      path: '/identity'
      fullPath: '/onboarding/identity'
      preLoaderRoute: typeof OnboardingIdentityRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/habit-type': {
      id: '/onboarding/habit-type'
      path: '/habit-type'
      fullPath: '/onboarding/habit-type'
      preLoaderRoute: typeof OnboardingHabitTypeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/habit-build': {
      id: '/onboarding/habit-build'
      path: '/habit-build'
      fullPath: '/onboarding/habit-build'
      preLoaderRoute: typeof OnboardingHabitBuildRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingHabitBuildRoute: typeof OnboardingHabitBuildRoute
  OnboardingHabitTypeRoute: typeof OnboardingHabitTypeRoute
  OnboardingIdentityRoute: typeof OnboardingIdentityRoute
  OnboardingReminderRoute: typeof OnboardingReminderRoute
  OnboardingStrugglesRoute: typeof OnboardingStrugglesRoute
  OnboardingTinyRoute: typeof OnboardingTinyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingHabitBuildRoute: OnboardingHabitBuildRoute,
  OnboardingHabitTypeRoute: OnboardingHabitTypeRoute,
  OnboardingIdentityRoute: OnboardingIdentityRoute,
  OnboardingReminderRoute: OnboardingReminderRoute,
  OnboardingStrugglesRoute: OnboardingStrugglesRoute,
  OnboardingTinyRoute: OnboardingTinyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
